version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: socialnetwork123
      POSTGRES_DB: cinema
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cinema
networks:
  cinema:
    driver: bridge

volumes:
  postgres:
